[package]
name = "kuba"
version = "0.1.0"
authors = ["Kevin Greene <kgreenek@gmail.com>"]
edition = "2018"

[dependencies]
approx = "0.3.2"
byteorder = "1.3.1"
nalgebra = "0.18.0"
ndarray = "0.12.1"

[dev-dependencies]
kiss3d = "0.20.1"
