[package]
name = "kuba"
version = "0.1.0"
authors = ["Kevin Greene <kgreenek@gmail.com>"]
edition = "2018"

[dependencies]
approx = "0.3.2"
capnp = "0.9.5"
nalgebra = "0.18.0"
ndarray = "0.12.1"

[build-dependencies]
capnpc = "0.9.5"
